#!/bin/bash
# Set working directory
cd ~/Easter/Dev/Ext/Overlord
clear
echo

if [ "$1" == "pull" ]
then
    ./tools/scripts/pull.sh && exit
    exit
fi

if [ "$1" = "commit" ]
then
    ./tools/scripts/commit.sh && exit
    exit
fi

if [ "$1" = "deploy" ]
then
    ./tools/scripts/git/deploy.sh "$2" && exit
fi

if [ "$1" = "django" ]
then
    if [ "$2" = "purge" ]
    then
        ./tools/scripts/django/purge.sh && exit
    fi
    exit
fi

python3 run.py tools $@
echo
