# Generated by Django 4.0.7 on 2022-10-07 22:52

import core.library.time
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('aliases', models.TextField(default='')),
                ('image', models.TextField()),
                ('icon', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('types', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField()),
                ('info', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('client', models.TextField(default='')),
                ('website', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('requirements', models.TextField(default='')),
                ('applications', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.CharField(default=uuid.uuid1, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(default=core.library.time.get_datetime_string)),
                ('author_uuid', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('header', models.TextField(default='')),
                ('subheader', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('image', models.JSONField(default=dict)),
                ('link', models.URLField(default='')),
                ('body', models.TextField(default='')),
                ('interactions', models.JSONField(default=dict)),
                ('comments', models.JSONField(default=dict)),
                ('public', models.BooleanField(default=False)),
                ('custom_tags', models.TextField(default='')),
                ('custom_values', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('categories', models.TextField(default='')),
                ('images', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('ingredients', models.JSONField()),
                ('utensils', models.JSONField()),
                ('approvals', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('names', models.TextField(default='')),
                ('display_name', models.TextField(default='')),
                ('display_image', models.URLField(default='https://www.easter.company/static/eastercompany/favicon.ico')),
                ('date_of_birth', models.DateTimeField()),
                ('date_joined', models.DateTimeField(default=core.library.time.get_datetime_string)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(default=None)),
                ('email', models.EmailField(default='', max_length=254)),
                ('sms', models.TextField(default='')),
                ('sent', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=36)),
                ('created_on', models.DateTimeField(default=core.library.time.get_datetime_string)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(unique=True)),
                ('sms', models.TextField(unique=True)),
                ('key', models.TextField()),
                ('permissions', models.IntegerField(default=0)),
                ('session', models.TextField(unique=True)),
                ('last_activity', models.DateTimeField(default=core.library.time.get_datetime_string)),
                ('panels', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtensilModel',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('aliases', models.TextField(default='')),
                ('icon', models.TextField(default='')),
            ],
        ),
    ]
