# Generated by Django 4.0.7 on 2022-10-07 22:53

import core.library.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateTimeField(default=core.library.time.get_datetime_string),
        ),
    ]
