# Generated by Django 4.0.7 on 2022-10-07 15:59

import core.library.time
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('sms', models.TextField(default='')),
                ('sent', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=36)),
                ('created_on', models.DateTimeField(default=core.library.time.get_datetime_string)),
            ],
        ),
    ]
