# Generated by Django 2.2 on 2021-01-14 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(editable=False)),
                ('head', models.TextField(default='untitled')),
                ('image', models.FileField(null=True, upload_to='./data')),
                ('body', models.TextField(default='content')),
                ('likes', models.IntegerField(default=0)),
                ('laughs', models.IntegerField(default=0)),
                ('sads', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
