# Generated by Django 4.0.3 on 2022-04-27 13:33

import core.library.time
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField()),
                ('info', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('client', models.TextField(default='')),
                ('website', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('requirements', models.TextField(default='')),
                ('applications', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.CharField(default=uuid.uuid1, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(default=core.library.time.get_datetime_str)),
                ('author_uuid', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('header', models.TextField(default='')),
                ('subheader', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('image', models.JSONField(default=dict)),
                ('link', models.URLField(default='')),
                ('body', models.TextField(default='')),
                ('interactions', models.JSONField(default=dict)),
                ('comments', models.JSONField(default=dict)),
                ('public', models.BooleanField(default=False)),
                ('custom_tags', models.TextField(default='')),
                ('custom_values', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(unique=True)),
                ('sms', models.TextField(blank=True, null=True, unique=True)),
                ('key', models.TextField()),
                ('authenticated_email', models.BooleanField(default=False)),
                ('authenticated_sms', models.BooleanField(default=False)),
                ('permissions', models.IntegerField(blank=True, null=True)),
                ('session', models.TextField(unique=True)),
                ('last_activity', models.DateTimeField(default=core.library.time.get_datetime_str)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField(default='')),
                ('middle_names', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('display_image', models.TextField(default='')),
                ('display_name', models.TextField(blank=True, default='', null=True)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField(default=core.library.time.get_datetime_str)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
