# Generated by Django 2.2 on 2020-12-24 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField()),
                ('uid', models.TextField()),
                ('head', models.TextField(default='untitled')),
                ('body', models.TextField(default='content')),
                ('likes', models.IntegerField(default=0)),
                ('laughs', models.IntegerField(default=0)),
                ('sads', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
